name: repricer
services:
  optiguardfront:
    image: test-spg-agency:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - test-spg-agency
      args:
        - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
    restart: unless-stopped
    networks:
      - dokploy-network
networks:
  backend:
    driver: bridge
    # Включить если кластстер
    # external: true
  dokploy-network:
    external: true
